version: '2'
services:
  brocker:
    image: webcenter/activemq:5.14.2
    ports:
      - "8161:8161"
      - "61613:61613"
    environment:
      ACTIVEMQ_MIN_MEMORY: "512"
      ACTIVEMQ_MAX_MEMORY: "2048"

  receiver_web:
    image: nginx:alpine
    volumes: 
      - ./receiver_nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./domain.crt:/domain.crt:ro
      - ./domain.key:/domain.key:ro
    ports:
      - "8081:80"
      - "4431:443"
  
  talkative_web:
    image: nginx:alpine
    volumes: 
      - ./talkative_nginx.conf:/etc/nginx/conf.d/default.conf:ro

    ports:
      - "8091:80"

  
  receiver_app:
    build: receiver_app
    ports:
      - "8082:80"
    environment:
      BROCKER_HOST: "brocker"
      BROCKER_PORT: "61613"
  
  talkative_app:
    build: talkative_app
    ports:
      - "8092:80"
    environment:
      BROCKER_HOST: "brocker"
      BROCKER_PORT: "61613"

    
    